### ISSUE TITLE
Issue with case sensitivy file in docs/ ?

### ISSUE THREAD

**Issue by lkhphuc** [cgarciae/treex#57]
Hi, I'm trying to implement the LayerNorm and GroupNorm function, but Git on my Mac doesn't like the case-sensitive file in `docs/api/Mapping.md` and `docs/api/mapping.md` for example.

After some combination of my stupidity and pre-commit magic, I have lost my change to LayerNorm and GroupNorm, yet still unable to make a commit, due to these case-sensitive files.

I wonder if those files case-sensitive files are necessary, or are just some old artifacts that can be removed now?
If those files are actually not duplicated then I guess my best bet to commit changes to this repo would be to make it via Github website, or create a special case-sensitive volume on my Mac for this repo.

**Comment by cgarciae** [comment]
> I wonder if those files case-sensitive files are necessary, or are just some old artifacts that can be removed now?

For now you can remove this. There is code inplace to automatically regenerate `docs/api`.

> If those files are actually not duplicated then I guess my best bet to commit changes to this repo would be to make it via Github website, or create a special case-sensitive volume on my Mac for this repo.

Would this help you? https://coderwall.com/p/5w3jca/git-case-sensitivity-on-os-x

**Comment by cgarciae** [comment]
Forgot, thanks for doing this! Having LayerNorm and GroupNorm would be super useful.

**Comment by lkhphuc** [comment]
Thanks. The git config doesn't help.
 I ended up creating a case-sensitive volume on my Mac. Using Disk Utility was rather easy and straightforward.
